/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.boundary;

import com.controller.*;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextArea;

/**
 *
 * @author Asus
 */
public class generateCovidReportUI extends javax.swing.JFrame {

    /**
     * Creates new form generateCovidReportUI
     */
    JFrame frame = new JFrame();
    JButton Backbutton = new JButton("Back");
    JPanel reportPanel = new JPanel();
    String positive,population;
    SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");  
    Date date = new Date(); 
    
    
    public generateCovidReportUI() {
        initComponents();     
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // to exit out of the application
        this.setTitle("Generate Reported Cases"); // set title of the this
        this.setResizable(true); //prevent the window from being resized
        this.setSize(600, 200); // set the X and Y dimension of the window

        this.getContentPane(); // change the color of the window background
        this.setLayout(new FlowLayout(FlowLayout.CENTER));  // set the lay out to FlowLayout
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        
        
        generateCovidReportController gcrc = new generateCovidReportController();
        String report = gcrc.getReport();
        
        
        JTextArea vaccReport = new JTextArea(report,7,30);
        vaccReport.setFont(new Font("Serif", Font.ITALIC, 16));
        vaccReport.setLineWrap(true); 
        vaccReport.setWrapStyleWord(true);
        vaccReport.setOpaque(false);
        vaccReport.setEditable(false);
        //vaccReport.setBackground(Color.WHITE);

        reportPanel.add(vaccReport);

        this.add(reportPanel);
        this.pack();
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 137, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
