/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.boundary;

import com.boundary.*;
import com.controller.updateUserController;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Asus
 */
public class updateUserUI extends javax.swing.JFrame {

    /**
     * Creates new form updateUserUI
     */
    JLabel NRIC;
    JTextField NRICTextField;
    JLabel pword;
    JTextField pwordField;
    JLabel firstname;
    JTextField firstnamefield;
    JLabel lastname;
    JTextField lastnamefield;
    JLabel Number;
    JTextField NumberField;
    JLabel Emailz;
    JTextField emailField;
    JLabel gender;
    JLabel dob;
    JTextField genderField;
    JTextField dobField;
    JLabel vaccinated;
    JTextField vaccinatedfield;
    JLabel email;
    JTextField emailfield;
    JLabel covid_status;
    JTextField covid_statusField;
    JLabel vaccineType;
    JTextField vaccineTypeField;
    JLabel certNumber;
    JTextField certNumberField;
    JLabel apptDate;
    JTextField apptDateField;
    JLabel location;
    JTextField locationField;
    
    String acctType ;
    String username;
    
    
    
    public updateUserUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountTypeLabel = new javax.swing.JLabel();
        acctSelection = new javax.swing.JComboBox<String>();
        selectAcct = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        updateButton = new javax.swing.JButton();
        Backbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        accountTypeLabel.setText("Account Type");

        acctSelection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Public", "Business", "Health Staff" }));

        selectAcct.setText("Confirm Selection");
        selectAcct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAcctActionPerformed(evt);
            }
        });

        updateButton.setText("Update User");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        Backbutton.setText("Back");
        Backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(updateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Backbutton)
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton)
                    .addComponent(Backbutton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(accountTypeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(acctSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(selectAcct)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acctSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountTypeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectAcct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectAcctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAcctActionPerformed
        // TODO add your handling code here:
        acctType = String.valueOf(acctSelection.getSelectedItem());
        
        if(acctType.equals("Public"))
        {
            NRIC = new JLabel("Public NRIC : ");
            NRIC.setBounds(10,20,80,25);
            NRIC.setForeground(Color.WHITE);
            jPanel1.add(NRIC);
            NRIC.setVisible(true);

            //NRIC text Field
            NRICTextField = new JTextField(30);
            NRICTextField.setBounds(100,20,80,25);
            jPanel1.add(NRICTextField);
            NRICTextField.setVisible(true);

            //Password
            pword = new JLabel("Password : ");
            pword.setBounds(10,40,80,25);
            pword.setForeground(Color.WHITE);
            jPanel1.add(pword);
            pword.setVisible(true);


            //Password textField
            pwordField = new JTextField(30);
            pwordField.setBounds(100,40,180,25);
            jPanel1.add(pwordField);
            pwordField.setVisible(true);

            //firstname
            vaccinated = new JLabel("Vaccinated : ");
            vaccinated.setBounds(10,60,80,25);
            vaccinated.setForeground(Color.WHITE);
            jPanel1.add(vaccinated);
            vaccinated.setVisible(true);
            


            //firstname textField
            vaccinatedfield = new JTextField(30);
            vaccinatedfield.setBounds(100,60,180,25);
            jPanel1.add(vaccinatedfield);
            vaccinatedfield.setVisible(true);

            //email
            email = new JLabel("Email : ");
            email.setBounds(10,80,80,25);
            email.setForeground(Color.WHITE);
            jPanel1.add(email);
            email.setVisible(true);


            //email textField
            emailfield = new JTextField(30);
            emailfield.setBounds(100,80,180,25);
            jPanel1.add(emailfield);
            emailfield.setVisible(true);

            //covid_status
            covid_status = new JLabel("Covid status : ");
            covid_status.setBounds(10,100,80,25);
            covid_status.setForeground(Color.WHITE);
            jPanel1.add(covid_status);
            covid_status.setVisible(true);


            //covid_status textField
            covid_statusField = new JTextField(30);
            covid_statusField.setBounds(100,100,180,25);
            jPanel1.add(covid_statusField);
            covid_statusField.setVisible(true);

            //vaccineType
            vaccineType = new JLabel("Vaccine Type: ");
            vaccineType.setBounds(10,120,80,25);
            vaccineType.setForeground(Color.WHITE);
            jPanel1.add(vaccineType);
            vaccineType.setVisible(true);


            //vaccineType textField
            vaccineTypeField = new JTextField(30);
            vaccineTypeField.setBounds(100,120,180,25);
            jPanel1.add(vaccineTypeField);
            vaccineTypeField.setVisible(true);
            
            //certNumber
            certNumber = new JLabel("Certificate Number : ");
            certNumber.setBounds(10,140,80,25);
            certNumber.setForeground(Color.WHITE);
            jPanel1.add(certNumber);
            certNumber.setVisible(true);


            //vaccineType textField
            certNumberField = new JTextField(30);
            certNumberField.setBounds(100,140,180,25);
            jPanel1.add(certNumberField);
            certNumberField.setVisible(true);
            
            //apptDate
            apptDate = new JLabel("Appointment Date : ");
            apptDate.setBounds(10,160,80,25);
            apptDate.setForeground(Color.WHITE);
            jPanel1.add(apptDate);
            apptDate.setVisible(true);


            //vaccineType textField
            apptDateField = new JTextField(30);
            apptDateField.setBounds(100,160,180,25);
            jPanel1.add(apptDateField);
            apptDateField.setVisible(true);
            
            
            selectAcct.setVisible(true);
            jPanel1.revalidate();
            jPanel1.repaint();

 

        }
        if(acctType.equals("Business"))
        {
            NRIC = new JLabel("Username: ");
            NRIC.setBounds(10,20,80,25);
            NRIC.setForeground(Color.WHITE);
            jPanel1.add(NRIC);
            NRIC.setVisible(true);

            //NRIC text Field
            NRICTextField = new JTextField(30);
            NRICTextField.setBounds(100,20,180,25);
            jPanel1.add(NRICTextField);
            NRICTextField.setVisible(true);

            //Password
            pword = new JLabel("Password : ");
            pword.setBounds(10,40,80,25);
            pword.setForeground(Color.WHITE);
            jPanel1.add(pword);
            pword.setVisible(true);


            //Password textField
            pwordField = new JTextField(30);
            pwordField.setBounds(100,40,180,25);
            jPanel1.add(pwordField);
            pwordField.setVisible(true);


            //Businessname
            lastname = new JLabel("Business_name : ");
            lastname.setBounds(10,60,80,25);
            lastname.setForeground(Color.WHITE);
            jPanel1.add(lastname);
            lastname.setVisible(true);


            //Businessname textField
            lastnamefield = new JTextField(30);
            lastnamefield.setBounds(100,60,180,25);
            jPanel1.add(lastnamefield);
            lastnamefield.setVisible(true);

            //Business Number
            Number = new JLabel("Number : ");
            Number.setBounds(10,80,80,25);
            Number.setForeground(Color.WHITE);
            jPanel1.add(Number);
            Number.setVisible(true);


            //Business Number textField
            NumberField = new JTextField(30);
            NumberField.setBounds(100,80,180,25);
            jPanel1.add(NumberField);
            NumberField.setVisible(true);

            //email
            Emailz = new JLabel("Email : ");
            Emailz.setBounds(10,100,80,25);
            Emailz.setForeground(Color.WHITE);
            jPanel1.add(Emailz);
            Emailz.setVisible(true);


            //email textField
            emailField = new JTextField(30);
            emailField.setBounds(100,100,180,25);
            jPanel1.add(emailField);
            emailField.setVisible(true);
            
            location = new JLabel("Location : ");
            location.setBounds(10,120,80,25);
            location.setForeground(Color.WHITE);
            jPanel1.add(location);
            location.setVisible(true);

           
            locationField = new JTextField(30);
            locationField.setBounds(100,120,180,25);
            jPanel1.add(locationField);
            locationField.setVisible(true);
            
            selectAcct.setVisible(true);
            jPanel1.revalidate();
            jPanel1.repaint();


        }
        if(acctType.equals("Health Staff"))
        {
            NRIC = new JLabel("Username of Staff : ");
            NRIC.setBounds(10,20,80,25);
            NRIC.setForeground(Color.WHITE);
            jPanel1.add(NRIC);
            NRIC.setVisible(true);

            //NRIC text Field
            NRICTextField = new JTextField(30);
            NRICTextField.setBounds(100,20,180,25);
            jPanel1.add(NRICTextField);
            NRICTextField.setVisible(true);

            //Password
            pword = new JLabel("Password : ");
            pword.setBounds(10,40,80,25);
            pword.setForeground(Color.WHITE);
            jPanel1.add(pword);
            pword.setVisible(true);


            //Password textField
            pwordField = new JTextField(30);
            pwordField.setBounds(100,40,180,25);
            jPanel1.add(pwordField);
            pwordField.setVisible(true);

            //firstname
            firstname = new JLabel("First Name : ");
            firstname.setBounds(10,60,80,25);
            firstname.setForeground(Color.WHITE);
            jPanel1.add(firstname);
            firstname.setVisible(true);


            //firstname textField
            firstnamefield = new JTextField(30);
            firstnamefield.setBounds(100,60,180,25);
            jPanel1.add(firstnamefield);
            firstnamefield.setVisible(true);

            //lastname
            lastname = new JLabel("Last Name : ");
            lastname.setBounds(10,80,80,25);
            lastname.setForeground(Color.WHITE);
            jPanel1.add(lastname);
            lastname.setVisible(true);


            //lastname textField
            lastnamefield = new JTextField(30);
            lastnamefield.setBounds(100,80,180,25);
            jPanel1.add(lastnamefield);
            lastnamefield.setVisible(true);

            //User Number
            Number = new JLabel("Number : ");
            Number.setBounds(10,100,80,25);
            Number.setForeground(Color.WHITE);
            jPanel1.add(Number);
            Number.setVisible(true);


            //User Number textField
            NumberField = new JTextField(30);
            NumberField.setBounds(100,100,180,25);
            jPanel1.add(NumberField);
            NumberField.setVisible(true);

            //email
            Emailz = new JLabel("Email : ");
            Emailz.setBounds(10,120,80,25);
            Emailz.setForeground(Color.WHITE);
            jPanel1.add(Emailz);
            Emailz.setVisible(true);


            //email textField
            emailField = new JTextField(30);
            emailField.setBounds(100,120,180,25);
            jPanel1.add(emailField);
            emailField.setVisible(true);
            
            selectAcct.setVisible(true);
            jPanel1.revalidate();
            jPanel1.repaint();

        }
        
    }//GEN-LAST:event_selectAcctActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        if(acctType.equals("Public"))
        {
            String username = NRICTextField.getText();
            String vaccinated = vaccinatedfield.getText();
            String pword = pwordField.getText();
            String covid_status = covid_statusField.getText();
            String vaccineType = vaccineTypeField.getText();
            String certNumber= certNumberField.getText();
            String apptdate = apptDateField.getText();
            
            ArrayList userDetails = new ArrayList<String>();
            userDetails.add(username);
            userDetails.add(vaccinated);
            userDetails.add(pword);
            userDetails.add(covid_status);
            userDetails.add(vaccineType);
            userDetails.add(certNumber);
            userDetails.add(apptdate);
            
            updateUserController cuC = new updateUserController();
            boolean result = cuC.updateUser("Public", userDetails);
            if(result == true)
            {
                JOptionPane.showMessageDialog(updateButton, "Account Updated Succesfully");
            }
            else
            {
                JOptionPane.showMessageDialog(updateButton, "Failed to update account", "Error",
                             JOptionPane.ERROR_MESSAGE);
            }
            
            
            
        }
        if(acctType.equals("Business"))
        {
            String username = NRICTextField.getText();
            String password = pwordField.getText();
            String bizname = lastnamefield.getText();
            String biznum = NumberField.getText();
            String bizEmail = emailField.getText();
            String locationStr = locationField.getText();
            
            ArrayList userDetails = new ArrayList<String>();
            userDetails.add(username);
            userDetails.add(password);
            userDetails.add(bizname);
            userDetails.add(biznum);
            userDetails.add(bizEmail);
            userDetails.add(locationStr);
            
             updateUserController cuC = new updateUserController();
            boolean result = cuC.updateUser("Business", userDetails);
            if(result == true)
            {
                JOptionPane.showMessageDialog(updateButton, "Account Updated Succesfully");
            }
            else
            {
                JOptionPane.showMessageDialog(updateButton, "Failed to update account", "Error",
                             JOptionPane.ERROR_MESSAGE);
            }
            
            
        }
        if(acctType.equals("Health Staff"))
        {
            String username = NRICTextField.getText();
            String password = pwordField.getText();
            String fname = firstnamefield.getText();
            String lname = lastnamefield.getText();
            String number = NumberField.getText();
            String email = emailField.getText();
            
            ArrayList userDetails = new ArrayList<String>();
            userDetails.add(username);
            userDetails.add(password);
            userDetails.add(fname);
            userDetails.add(lname);
            userDetails.add(number);
            userDetails.add(email);
            
             updateUserController cuC = new updateUserController();
            boolean result = cuC.updateUser("Health Staff", userDetails);
            if(result == true)
            {
                JOptionPane.showMessageDialog(updateButton, "Account Updated Succesfully");
            }
            else
            {
                JOptionPane.showMessageDialog(updateButton, "Failed to update account", "Error",
                             JOptionPane.ERROR_MESSAGE);
            }
            
            
        }
        
    }//GEN-LAST:event_updateButtonActionPerformed

    private void BackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbuttonActionPerformed
        // TODO add your handling code here:
        OrganisationUserUI org = new OrganisationUserUI(username);
        org.setVisible(true);
        org.pack();
        org.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_BackbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(updateUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(updateUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(updateUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(updateUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new updateUserUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbutton;
    private javax.swing.JLabel accountTypeLabel;
    private javax.swing.JComboBox<String> acctSelection;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton selectAcct;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
